const cars=[
{name:"Porsche 911 Carrera",score:92,perf:94,looks:96,daily:84},{name:"BMW M3 Competition",score:91,perf:92,looks:88,daily:91},{name:"Mercedes-AMG C 63",score:89,perf:91,looks:90,daily:88},{name:"Nissan GT-R",score:90,perf:96,looks:87,daily:78},{name:"Toyota GR Supra",score:87,perf:88,looks:91,daily:82},{name:"Ford Mustang GT",score:85,perf:88,looks:94,daily:80},{name:"Honda Civic Type R",score:84,perf:86,looks:89,daily:93},{name:"Audi RS 3",score:88,perf:90,looks:86,daily:92}];
const $=id=>document.getElementById(id), base=$("base"),carA=$("carA"),carB=$("carB"),drive=$("drive"),mission=$("mission"),style=$("style"),budgetSlider=$("budgetSlider");
cars.forEach(c=>[base,carA,carB].forEach(s=>{let o=document.createElement("option");o.value=c.name;o.textContent=c.name;s.appendChild(o)}));base.value=cars[0].name;carA.value=cars[0].name;carB.value=cars[1].name;
const getCar=n=>cars.find(c=>c.name===n);
function scoreBuild(){const c=getCar(base.value),d=drive.value,m=mission.value,b=+budgetSlider.value;let p=c.perf,l=c.looks,dy=c.daily;if(d==="AWD")p+=3;if(d==="FWD")p-=3;if(m==="speed")p+=5;if(m==="looks")l+=7;if(m==="daily")dy+=7;if(m==="track")p+=8;if(document.querySelector('[data-up="engine"]').classList.contains("active"))p+=2;if(style.value==="Luxury")dy+=3;if(style.value==="Track")p+=3;if(style.value==="Stealth")l+=2;p=Math.min(99,p);l=Math.min(99,l);dy=Math.min(99,dy);let s=Math.round((p+l+dy)/3+Math.min(4,(b-70000)/60000));s=Math.max(50,Math.min(99,s));$("score").textContent=s;document.querySelector(".score-ring").style.setProperty("--score",s+"%");$("perf").style.width=p+"%";$("looks").style.width=l+"%";$("daily").style.width=dy+"%";$("budget").textContent="$"+b.toLocaleString();const v=s>=94?["Absolute monster.","You built something that would dominate a group chat."]:s>=89?["Certified menace.","Fast, stylish, and just sensible enough to pretend this is a daily."]:s>=84?["Balanced menace.","Fast enough to scare people, civilized enough to drive home."]:["Fun spec.","Not perfect on paper — which is exactly why it has personality."];$("verdict").textContent=v[0];$("verdictText").textContent=v[1];$("saved").textContent="NOT SAVED";return{car:c.name,score:s,p,l,dy,budget:b,drive:d,mission:m,style:style.value}}
[base,drive,mission,style,budgetSlider].forEach(x=>x.addEventListener("input",scoreBuild));document.querySelectorAll(".chip").forEach(x=>x.onclick=()=>{x.classList.toggle("active");scoreBuild()});
function saveBuild(){const b=scoreBuild();let g=JSON.parse(localStorage.getItem("carlabGarage")||"[]");g.unshift(b);g=g.slice(0,9);localStorage.setItem("carlabGarage",JSON.stringify(g));$("saved").textContent="SAVED ✓";renderGarage()}
function renderGarage(){const g=JSON.parse(localStorage.getItem("carlabGarage")||"[]");$("garageGrid").innerHTML=g.length?g.map((x,i)=>`<div class="garage-item"><small>${x.style.toUpperCase()} · ${x.drive}</small><h3>${x.car}</h3><div class="score">${x.score}/100</div><small>$${x.budget.toLocaleString()} budget</small><br><button class="ghost" onclick="removeBuild(${i})">Remove</button></div>`).join(""):`<div class="garage-empty">Your garage is empty.<br><br>Build something ridiculous and save it.</div>`}
function removeBuild(i){let g=JSON.parse(localStorage.getItem("carlabGarage")||"[]");g.splice(i,1);localStorage.setItem("carlabGarage",JSON.stringify(g));renderGarage()}
function shareBuild(){const b=scoreBuild(),t=`I built a ${b.car} on CarLab and scored ${b.score}/100. ${b.style} spec, ${b.drive}, $${b.budget.toLocaleString()} budget. Can you beat it?`;if(navigator.share)navigator.share({title:"My CarLab Build",text:t}).catch(()=>{});else navigator.clipboard?.writeText(t).then(()=>alert("Build copied — paste it anywhere!"))}
function runBattle(){const a=getCar(carA.value),b=getCar(carB.value);$("statA").textContent=a.score;$("statB").textContent=b.score;const w=a.score>b.score?a:b,m=Math.abs(a.score-b.score);$("battleResult").classList.remove("hidden");$("battleResult").innerHTML=`🏆 <strong>${m?w.name+" wins.":"Dead even."}</strong><br><small>${m?m+" point"+(m===1?"":"s")+" ahead.":"Your taste decides."}</small>`}
const questions=[{clue:"This car is famous for its flat-six engine and rear-engine layout.",ans:"Porsche 911 Carrera",opts:["Porsche 911 Carrera","BMW M3 Competition","Honda Civic Type R","Ford Mustang GT"]},{clue:"This Japanese sports coupe is a modern successor to a legendary nameplate.",ans:"Toyota GR Supra",opts:["Audi RS 3","Toyota GR Supra","Mercedes-AMG C 63","Ford Mustang GT"]},{clue:"This hot hatch is front-wheel drive and built by Honda.",ans:"Honda Civic Type R",opts:["Honda Civic Type R","Nissan GT-R","Porsche 911 Carrera","BMW M3 Competition"]},{clue:"This American icon is known for its V8 GT versions and long-running pony-car history.",ans:"Ford Mustang GT",opts:["Ford Mustang GT","Audi RS 3","Toyota GR Supra","Nissan GT-R"]}];let qi=0,st=0;
function renderQuestion(){const q=questions[qi%questions.length];$("qCount").textContent=`QUESTION ${(qi%questions.length)+1}`;$("streak").textContent=st;$("clue").textContent=q.clue;$("quizFeedback").textContent="";$("answers").innerHTML=q.opts.map(o=>`<button onclick="answer('${o.replaceAll("'","\\'")}')">${o}</button>`).join("")}
function answer(x){const q=questions[qi%questions.length];document.querySelectorAll(".answers button").forEach(b=>{if(b.textContent===q.ans)b.classList.add("correct");if(b.textContent===x&&x!==q.ans)b.classList.add("wrong")});if(x===q.ans){st++;$("quizFeedback").textContent="✓ Correct. Keep the streak alive.";$("quizFeedback").style.color="var(--accent)"}else{st=0;$("quizFeedback").textContent=`Not quite — it was the ${q.ans}.`;$("quizFeedback").style.color="#e66"}$("streak").textContent=st}
function nextQuestion(){qi++;renderQuestion()}function scrollToId(id){$(id).scrollIntoView({behavior:"smooth"})}$("year").textContent=new Date().getFullYear();scoreBuild();renderGarage();renderQuestion();